const {Router}=require('express')
const router=Router()
const auth=require('./middleware/auth')

const apirouter=require('./router/api')
const pagerouter=require('./router/page')
const user=require('./router/user')
const attribute=require('./router/attribute')
const stuff=require('./router/stuff')
const product=require('./router/product')
const faqs=require('./router/faqs')
const category=require('./router/category')
const status=require('./router/status')
const technology=require('./router/technology')
const slider=require('./router/slider')
const company_info=require('./router/company_info')


router.use('/api',apirouter)
router.use('/attribute',auth,attribute)
router.use('/product',auth,product)
router.use('/slider',auth,slider)
router.use('/status',auth,status)
router.use('/stuff',auth,stuff)
router.use('/technology',auth,technology)
router.use('/company_info',auth,company_info)
router.use('/', pagerouter)
router.use('/',user)
router.use('/category',auth,category)
router.use('/faqs',auth,faqs)
module.exports=router
