const {Router}=require('express')
const router=Router()
const auth=require('./middleware/auth')

const apirouter=require('./router/api')
const pagerouter=require('./router/page')
const user=require('./router/user')
const attribute=require('./router/attribute')
const stuff=require('./router/stuff')
const product=require('./router/product')
const faqs=require('./router/faqs')
const category=require('./router/category')
const vacancy=require('./router/vacancy')

router.use('/api',apirouter)
router.use('/', pagerouter)
router.use('/',user)
router.use('/attribute',auth,attribute)
router.use('/product',auth,product)
router.use('/stuff',auth,stuff)
router.use('/vacancy',auth,vacancy)
router.use('/category',auth,category)
router.use('/faqs',auth,faqs)
module.exports=router
